version: "3"

services:
  app:
    command: >
      bash -c "poetry run python manage.py makemigrations && 
               poetry run python manage.py migrate && 
               poetry run python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - REDIS_HOST
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app


  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '5432:5432'

  redis:
    image: redis:6.0.7
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - '6379:6379'

  redis_insight:
    image: redis/redisinsight:latest
    restart: always
    volumes:
      - redis_insight:/data
    ports:
      - '5540:5540'

volumes:
  redis_volume_data:
  redis_insight: